### ISSUE TITLE
Method connect() always throw exeption

### ISSUE THREAD

**Issue by EnvOut** [delthas/JavaSkype#41]
Skype skype = new Skype("oldSkype.login","pass");
 skype.connect();

Every time after calling .connect() i have exeption:
**Error thrown during connection. Check your credentials?**

Also propblem with 
fr.delthas.skype.ParseException: org.json.JSONException: JSONObject["name"] not found.

**Comment by hyligan** [comment]
I've got too this trouble :(
++ LOGS ++
џэт 04, 2018 2:20:33 PM fr.delthas.skype.Skype connect
FINE: Connecting to Skype
џэт 04, 2018 2:20:33 PM fr.delthas.skype.Skype reset
FINEST: Resetting the Skype object
џэт 04, 2018 2:20:33 PM fr.delthas.skype.NotifConnector generateEPID
FINEST: Generated EPID: c8367306-4007-a127-503b-f226472fa683
џэт 04, 2018 2:20:33 PM fr.delthas.skype.LiveConnector refreshTokens
FINER: Refreshing tokens
џэт 04, 2018 2:20:36 PM fr.delthas.skype.LiveConnector refreshTokens
FINER: Refreshed live tokens successfully
џэт 04, 2018 2:20:36 PM fr.delthas.skype.WebConnector refreshTokens
FINER: Refreshing tokens
џэт 04, 2018 2:20:36 PM fr.delthas.skype.WebConnector generateToken
FINEST: Getting Microsoft token
џэт 04, 2018 2:20:36 PM fr.delthas.skype.WebConnector sendRequest
FINEST: Sending POST request at https://api.skype.com/rps/skypetoken
џэт 04, 2018 2:20:36 PM fr.delthas.skype.WebConnector sendRequest
FINE: No token sent for the request at: https://api.skype.com/rps/skypetoken
џэт 04, 2018 2:20:37 PM fr.delthas.skype.WebConnector sendRequest
FINEST: Sending GET request at https://api.skype.com/users/self/profile
џэт 04, 2018 2:20:37 PM fr.delthas.skype.WebConnector sendRequest
FINEST: Sending GET request at https://contacts.skype.com/contacts/v2/users/live:itemailassistant/contacts

how fix?

**Comment by morgancdip** [comment]
I have also a mistake:
mars 29, 2018 10:28:24 AM fr.delthas.skype.Skype connect
Précis: Connecting to Skype
mars 29, 2018 10:28:24 AM fr.delthas.skype.Skype reset
Le plus précis: Resetting the Skype object
mars 29, 2018 10:28:24 AM fr.delthas.skype.NotifConnector generateEPID
Le plus précis: Generated EPID: 23d1b915-ec3f-76f8-fd0d-a9f75bef35ac
mars 29, 2018 10:28:24 AM fr.delthas.skype.LiveConnector refreshTokens
Plus précis: Refreshing tokens
mars 29, 2018 10:28:29 AM fr.delthas.skype.LiveConnector refreshTokens
Plus précis: Refreshed live tokens successfully
mars 29, 2018 10:28:29 AM fr.delthas.skype.WebConnector refreshTokens
Plus précis: Refreshing tokens
mars 29, 2018 10:28:29 AM fr.delthas.skype.WebConnector generateToken
Le plus précis: Getting Microsoft token
mars 29, 2018 10:28:29 AM fr.delthas.skype.WebConnector sendRequest
Le plus précis: Sending POST request at https://api.skype.com/rps/skypetoken
mars 29, 2018 10:28:29 AM fr.delthas.skype.WebConnector sendRequest
Précis: No token sent for the request at: https://api.skype.com/rps/skypetoken
mars 29, 2018 10:28:29 AM fr.delthas.skype.WebConnector sendRequest
Le plus précis: Sending GET request at https://api.skype.com/users/self/profile
mars 29, 2018 10:28:30 AM fr.delthas.skype.WebConnector sendRequest
Le plus précis: Sending GET request at https://contacts.skype.com/contacts/v2/users/live:test/contacts

Error thrown during connection. Check your credentials?
fr.delthas.skype.ParseException: org.json.JSONException: End of input at character 0 of 

url "https://contacts.skype.com/contacts/v2/users/live:test/contacts" return an empty string

I use this on android device and it had worked 5 times before, after always same mistake

**Comment by fabiodepin** [comment]
hello,
see my last commit, it's has been solved.
fabiodepin/JavaSkype@c3d3cd2

**Comment by delthas** [comment]
No, ignoring the contact username is probably not the right workaround.

**Comment by PURUS6233** [comment]
Hi! The same error still((
`java.io.IOException: Error thrown during connection. Check your credentials?
	at fr.delthas.skype.Skype.connect(Skype.java:164)
	at fr.delthas.skype.Skype.connect(Skype.java:124)`
`Caused by: fr.delthas.skype.ParseException: org.json.JSONException: JSONObject["name"] not found.
	at fr.delthas.skype.WebConnector.updateUser(WebConnector.java:163)
	at fr.delthas.skype.WebConnector.updateContacts(WebConnector.java:100)
	at fr.delthas.skype.WebConnector.refreshTokens(WebConnector.java:43)
	at fr.delthas.skype.Skype.connect(Skype.java:157)
	... 32 more
Caused by: org.json.JSONException: JSONObject["name"] not found.
	at org.json.JSONObject.get(JSONObject.java:471)
	at org.json.JSONObject.getJSONObject(JSONObject.java:636)
	at fr.delthas.skype.WebConnector.updateUser(WebConnector.java:149)
	... 35 more`
